### ISSUE TITLE
remove rogue console.log

### ISSUE THREAD

**Issue by clkent** [Brew-Brew/css-in-js-media#15]
Hello team Brew-Brew. Love using css-in-js-media, thank you for all of your work. 

I kept seeing "dd" popping up as I built my project and wasn't sure where it was coming from until doing a little digging and found it within `dist/index.js`. 

I've removed this from my project's instance but figured it was worth calling out here. I cloned the repo and removed this but can't push because I don't have access to contribute. Happy to do so if possible. 

Thank you!

**Comment by Brew-Brew** [comment]
@clkent First of all, thank you for using css-in-js-media and reporting issue :)And I will fix that issue now! Thank you :)

Next time, If you want to update my library, 
you can update by 
1. fork my repo 
2. push update to your repo 
3. make pull request

**Comment by Brew-Brew** [comment]
@clkent If you use version 1.0.14, you can use library without seeing useless log "dd" Thanks! :)
