### ISSUE TITLE
migrate to typescript

### ISSUE THREAD

**Issue by Brew-Brew** [Brew-Brew/css-in-js-media#5]
- migrate to typescript

**Comment by ZombieChowder11** [comment]
Has the library been migrated to Typescript ? Or is it still to be done ?

**Comment by Brew-Brew** [comment]
Hi @ZombieChowder11 ! It still to be done 🙇‍♂️

**Comment by Brew-Brew** [comment]
Done with https://github.com/Brew-Brew/css-in-js-media/pull/21
